name: Build BL2 and FIP

on:
  push:

jobs:
  generate_list:
    name: Generate build list
    runs-on: ubuntu-latest
    outputs:
      list: ${{ steps.list.outputs.list }}

    steps:
      - name: Checkout source tree
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Generate build list
        id: list
        run: |
          COMMIT="$(git log --pretty=format:"%H" -1 uboot-mtk-*/configs)"
          CONFIGS="$(git show --name-only "$COMMIT" | awk -F '/' '/^uboot.*defconfig$/ {printf "\"%s\",", $NF}' | sed 's/,$//')"
          JSON_LIST="{\"runner\": [\"ubuntu-latest\"],\"list\": [ \"mt7981_360t7_defconfig\", \"mt7981_abt_asr3000_defconfig\",\"mt7981_ax3000t_an8855_defconfig\",\"mt7981_ax3000t_defconfig\",\"mt7981_cetron_ct3003_defconfig\",\"mt7981_cmcc_a10_defconfig\",\"mt7981_cmcc_rax3000m-emmc_defconfig\",\"mt7981_cmcc_rax3000m_defconfig\",\"mt7981_cudy_tr3000-v1_defconfig\",\"mt7981_h3c_magic-nx30-pro_defconfig\",\"mt7981_imou_lc-hx3001_defconfig\",\"mt7981_jcg_q30_defconfig\",\"mt7981_konka_komi-a31_defconfig\",\"mt7981_livinet_zr-3020_defconfig\",\"mt7981_nokia_ea0326gmp_defconfig\",\"mt7981_wr30u_defconfig\",\"mt7986_jdcloud_re-cp-03_defconfig\",\"mt7986_netcore_n60-pro_defconfig\",\"mt7986_tplink_tl-xdr608x_defconfig\",\"mt7986_tplink_tl-xtr8488_defconfig\"]}"
          echo "$JSON_LIST" | jq .
          echo "list=$JSON_LIST" >> "$GITHUB_OUTPUT"
          {
 

  build:
    name: Build ${{ matrix.list }}
    needs: generate_list
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix: ${{ fromJson(needs.generate_list.outputs.list) }}
      fail-fast: false
      max-parallel: 15

    steps:
      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get install gcc-aarch64-linux-gnu build-essential flex bison libssl-dev device-tree-compiler

      - name: Checkout source tree
        uses: actions/checkout@v4

      - name: Build BL2 and FIP
        env:
          CONFIG: ${{ matrix.list }}
        run: |
          export SOC="${CONFIG%%_*}"
          BOARD="${CONFIG#*_}"
          export BOARD="${BOARD%_*}"
          mkdir -p "output"
          ./build.sh 2>&1 | tee "output/build.log"
          sha256sum "output"/* | sed "s|output/||" > "output/sha256sums"
          echo "ARTIFACT_NAME=$SOC-$BOARD" >> "$GITHUB_ENV"

      - name: Upload build outputs
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: output/*
